server:
  #默认端口
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

#文档配置
springdoc:
  #调试时平展对象参数
  default-flat-param-object: true

spring:

  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 1024MB
      # 所有上传文件最大大小
      max-request-size: 1024MB

  data:
    redis:
      host: 192.168.163.101
      port: 6379
      database: 0
      password: 123456

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.163.101:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password:
    #连接池配置
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称

  jackson:
    time-zone: GMT+8

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    #log实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://192.168.163.101:9000
  access-key: root
  secret-key: 12345678
  bucket-name: lease

